version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432/bclabs
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bclabs
    ports:
      - '5432:5432'
